/********************************************************************
* src/GEMDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/GEMDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableGEMDict();
extern void G__cpp_setup_inheritanceGEMDict();
extern void G__cpp_setup_typetableGEMDict();
extern void G__cpp_setup_memvarGEMDict();
extern void G__cpp_setup_globalGEMDict();
extern void G__cpp_setup_memfuncGEMDict();
extern void G__cpp_setup_funcGEMDict();
extern void G__set_cpp_environmentGEMDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "GEMDataStruct.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__GEMDictLN_TClass;
extern G__linked_taginfo G__GEMDictLN_TBuffer;
extern G__linked_taginfo G__GEMDictLN_TMemberInspector;
extern G__linked_taginfo G__GEMDictLN_TObject;
extern G__linked_taginfo G__GEMDictLN_GEMClusterStruct;
extern G__linked_taginfo G__GEMDictLN_HyCalClusterStruct;

/* STUB derived class for protected member access */
